# Generated by Django 4.2.2 on 2023-06-19 06:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[+-/%@$^&*()!:;]', inverse_match=True)])),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('rv_email', models.CharField(max_length=100, unique=True)),
                ('branch', models.CharField(max_length=50)),
                ('year_joined', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
                ('stud', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='student.student')),
            ],
            options={
                'db_table': 'skills',
            },
        ),
    ]
