# Generated by Django 4.2.2 on 2023-06-19 06:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator('[+-/%@$^&*()!:;]', inverse_match=True)])),
                ('phone', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('rv_email', models.CharField(max_length=100, null=True)),
                ('branch', models.CharField(max_length=50, null=True)),
                ('year_joined', models.DateField(null=True)),
                ('year_passed', models.DateField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumnus_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alumni',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Consultancy', 'Consultancy'), ('Finance', 'Finance'), ('Software Developer', 'Software Developer'), ('Data Analyst', 'Data Analyst'), ('Network Security', 'Network Security'), ('Cloud Computing', 'Cloud Computing'), ('IT project management', 'IT project management'), ('AI and ML', 'AI and ML'), ('others', 'others')], max_length=50, null=True)),
                ('salary', models.FloatField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(max_length=20)),
                ('alumnus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumni.alumni')),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Higherstudies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence'), ('Machine Learning', 'Machine Learning'), ('Cloud Computing', 'Cloud Computing'), ('Data Science', 'Data Science'), ('Computer Vision', 'Computer Vision'), ('Natural Language processing', 'Natural Language processing'), ('Marketing', 'Marketing'), ('Finance Systems', 'Finanace Systems'), ('IOT', 'IOT'), ('others', 'others')], max_length=100, null=True)),
                ('degree', models.CharField(choices=[('M Tech', 'M Tech'), ('MSc', 'MSc'), ('MBA', 'MBA'), ('Others', 'Others')], max_length=20, null=True)),
                ('location', models.CharField(max_length=20, null=True)),
                ('yearofgrad', models.DateField(max_length=10, null=True)),
                ('alumnus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumni.alumni')),
            ],
            options={
                'db_table': 'higherstudies',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('Enterprenuer', 'Enterprenuer'), ('Higher Studies', 'Higher Studies'), ('Job', 'Job'), ('Others', 'Others')], default='Job', max_length=20)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('alumnus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alumni.alumni')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
